;;; zoom-window-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from zoom-window.el

(autoload 'zoom-window-setup "zoom-window" "\
To work with elscreen or persp-mode.")
(autoload 'zoom-window-zoom "zoom-window" "\
Zoom the current window." t)
(register-definition-prefixes "zoom-window" '("zoom-window-"))

;;; End of scraped data

(provide 'zoom-window-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; zoom-window-autoloads.el ends here
