;;; lsp-intellij-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from lsp-intellij.el

(defface lsp-intellij-face-code-lens-run '((((background dark)) :background "dark green") (((background light)) :background "green")) "\
Face used for areas with a run configuration." :group 'lsp-intellij-faces)
(defface lsp-intellij-face-code-lens-test '((((background dark)) :background "saddle brown") (((background light)) :background "yellow")) "\
Face used for areas with a test configuration." :group 'lsp-intellij-faces)
(defface lsp-intellij-face-code-lens-test-pass '((((background dark)) :background "sea green") (((background light)) :background "green")) "\
Face used for areas with a passing test configuration." :group 'lsp-intellij-faces)
(defface lsp-intellij-face-code-lens-test-fail '((((background dark)) :background "firebrick") (((background light)) :background "red")) "\
Face used for areas with a failing test configuration." :group 'lsp-intellij-faces)
(defface lsp-intellij-face-code-lens-test-unknown '((((background dark)) :background "saddle brown") (((background light)) :background "yellow")) "\
Face used for areas with a test configuration an with unknown state." :group 'lsp-intellij-faces)
(register-definition-prefixes "lsp-intellij" '("lsp-intellij-"))

;;; End of scraped data

(provide 'lsp-intellij-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lsp-intellij-autoloads.el ends here
